// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cart.proto

package id.tunas.grocery.grpc;

public final class CartOuterClass {
  private CartOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Cart_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Cart_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_CartDetail_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_CartDetail_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_CartAndUserId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_CartAndUserId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_CartUserId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_CartUserId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_CartEmpty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_CartEmpty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_MultipleCartResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_MultipleCartResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\ncart.proto\022\005proto\032\016response.proto\"F\n\004C" +
      "art\022\n\n\002id\030\001 \001(\t\022\r\n\005total\030\002 \001(\r\022\022\n\nproduc" +
      "t_id\030\003 \001(\t\022\017\n\007user_id\030\004 \001(\t\"\260\001\n\nCartDeta" +
      "il\022\n\n\002id\030\001 \001(\t\022\014\n\004name\030\002 \001(\t\022\r\n\005price\030\003 " +
      "\001(\004\022\016\n\006weight\030\004 \001(\r\022\020\n\010category\030\005 \001(\t\022\020\n" +
      "\010per_unit\030\006 \001(\r\022\r\n\005total\030\007 \001(\r\022\021\n\timage_" +
      "url\030\010 \001(\t\022\022\n\nproduct_id\030\t \001(\t\022\017\n\007user_id" +
      "\030\n \001(\t\",\n\rCartAndUserId\022\n\n\002id\030\001 \001(\t\022\017\n\007u" +
      "ser_id\030\002 \001(\t\"\030\n\nCartUserId\022\n\n\002id\030\001 \001(\t\"\013" +
      "\n\tCartEmpty\"X\n\024MultipleCartResponse\022\016\n\006s",
      "tatus\030\001 \001(\t\022\017\n\007message\030\002 \001(\t\022\037\n\004data\030\003 \003" +
      "(\0132\021.proto.CartDetail2\244\001\n\013CartService\022$\n" +
      "\004Save\022\013.proto.Cart\032\017.proto.Response\022/\n\006D" +
      "elete\022\024.proto.CartAndUserId\032\017.proto.Resp" +
      "onse\022>\n\014FindByUserId\022\021.proto.CartUserId\032" +
      "\033.proto.MultipleCartResponseB(\n\025id.groce" +
      "ry.tunas.grpcP\001Z\r/service/cartb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ResponseOuterClass.getDescriptor(),
        }, assigner);
    internal_static_proto_Cart_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_Cart_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Cart_descriptor,
        new java.lang.String[] { "Id", "Total", "ProductId", "UserId", });
    internal_static_proto_CartDetail_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_CartDetail_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_CartDetail_descriptor,
        new java.lang.String[] { "Id", "Name", "Price", "Weight", "Category", "PerUnit", "Total", "ImageUrl", "ProductId", "UserId", });
    internal_static_proto_CartAndUserId_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_CartAndUserId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_CartAndUserId_descriptor,
        new java.lang.String[] { "Id", "UserId", });
    internal_static_proto_CartUserId_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_proto_CartUserId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_CartUserId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_proto_CartEmpty_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_proto_CartEmpty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_CartEmpty_descriptor,
        new java.lang.String[] { });
    internal_static_proto_MultipleCartResponse_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_proto_MultipleCartResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_MultipleCartResponse_descriptor,
        new java.lang.String[] { "Status", "Message", "Data", });
    ResponseOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
