// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cart.proto

package id.tunas.grocery.grpc;

public interface CartDetailOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.CartDetail)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>uint64 price = 3;</code>
   */
  long getPrice();

  /**
   * <code>uint32 weight = 4;</code>
   */
  int getWeight();

  /**
   * <code>string category = 5;</code>
   */
  java.lang.String getCategory();
  /**
   * <code>string category = 5;</code>
   */
  com.google.protobuf.ByteString
      getCategoryBytes();

  /**
   * <code>uint32 per_unit = 6;</code>
   */
  int getPerUnit();

  /**
   * <code>uint32 total = 7;</code>
   */
  int getTotal();

  /**
   * <code>string image_url = 8;</code>
   */
  java.lang.String getImageUrl();
  /**
   * <code>string image_url = 8;</code>
   */
  com.google.protobuf.ByteString
      getImageUrlBytes();

  /**
   * <code>string product_id = 9;</code>
   */
  java.lang.String getProductId();
  /**
   * <code>string product_id = 9;</code>
   */
  com.google.protobuf.ByteString
      getProductIdBytes();

  /**
   * <code>string user_id = 10;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 10;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();
}
