// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cart.proto

package id.tunas.grocery.grpc;

public interface CartOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Cart)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>uint32 total = 2;</code>
   */
  int getTotal();

  /**
   * <code>string product_id = 3;</code>
   */
  java.lang.String getProductId();
  /**
   * <code>string product_id = 3;</code>
   */
  com.google.protobuf.ByteString
      getProductIdBytes();

  /**
   * <code>string user_id = 4;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 4;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();
}
