// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: category.proto

package id.tunas.grocery.grpc;

public interface MultipleCategoryResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.MultipleCategoryResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>repeated .proto.Category data = 3;</code>
   */
  java.util.List<Category>
      getDataList();
  /**
   * <code>repeated .proto.Category data = 3;</code>
   */
  Category getData(int index);
  /**
   * <code>repeated .proto.Category data = 3;</code>
   */
  int getDataCount();
  /**
   * <code>repeated .proto.Category data = 3;</code>
   */
  java.util.List<? extends CategoryOrBuilder>
      getDataOrBuilderList();
  /**
   * <code>repeated .proto.Category data = 3;</code>
   */
  CategoryOrBuilder getDataOrBuilder(
      int index);
}
