// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package id.tunas.grocery.grpc;

public interface MultipleProductResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.MultipleProductResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>repeated .proto.Product data = 3;</code>
   */
  java.util.List<Product>
      getDataList();
  /**
   * <code>repeated .proto.Product data = 3;</code>
   */
  Product getData(int index);
  /**
   * <code>repeated .proto.Product data = 3;</code>
   */
  int getDataCount();
  /**
   * <code>repeated .proto.Product data = 3;</code>
   */
  java.util.List<? extends ProductOrBuilder>
      getDataOrBuilderList();
  /**
   * <code>repeated .proto.Product data = 3;</code>
   */
  ProductOrBuilder getDataOrBuilder(
      int index);
}
