// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cart.proto

package id.tunas.grocery.grpc;

public interface MultipleCartResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.MultipleCartResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>repeated .proto.CartDetail data = 3;</code>
   */
  java.util.List<CartDetail>
      getDataList();
  /**
   * <code>repeated .proto.CartDetail data = 3;</code>
   */
  CartDetail getData(int index);
  /**
   * <code>repeated .proto.CartDetail data = 3;</code>
   */
  int getDataCount();
  /**
   * <code>repeated .proto.CartDetail data = 3;</code>
   */
  java.util.List<? extends CartDetailOrBuilder>
      getDataOrBuilderList();
  /**
   * <code>repeated .proto.CartDetail data = 3;</code>
   */
  CartDetailOrBuilder getDataOrBuilder(
      int index);
}
