// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package id.tunas.grocery.grpc;

public final class ProductOuterClass {
  private ProductOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Product_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Product_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ProductId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ProductId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ProductEmpty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ProductEmpty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_ProductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_ProductResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_MultipleProductResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_MultipleProductResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rproduct.proto\022\005proto\032\016response.proto\032\016" +
      "category.proto\"\312\001\n\007Product\022\014\n\004name\030\001 \001(\t" +
      "\022\n\n\002id\030\002 \001(\t\022\020\n\010category\030\003 \001(\t\022\020\n\010imageU" +
      "rl\030\004 \001(\t\022\r\n\005price\030\005 \001(\004\022\016\n\006weight\030\006 \001(\r\022" +
      "\023\n\013category_id\030\007 \001(\t\022\020\n\010per_unit\030\010 \001(\004\022\023" +
      "\n\013description\030\t \001(\t\022\026\n\016is_recommended\030\n " +
      "\001(\010\022\016\n\006is_top\030\013 \001(\010\"\027\n\tProductId\022\n\n\002id\030\001" +
      " \001(\t\"\016\n\014ProductEmpty\"P\n\017ProductResponse\022" +
      "\016\n\006status\030\001 \001(\t\022\017\n\007message\030\002 \001(\t\022\034\n\004data" +
      "\030\003 \001(\0132\016.proto.Product\"X\n\027MultipleProduc",
      "tResponse\022\016\n\006status\030\001 \001(\t\022\017\n\007message\030\002 \001" +
      "(\t\022\034\n\004data\030\003 \003(\0132\016.proto.Product2\353\003\n\016Pro" +
      "ductService\0224\n\010FindById\022\020.proto.ProductI" +
      "d\032\026.proto.ProductResponse\022>\n\007FindAll\022\023.p" +
      "roto.ProductEmpty\032\036.proto.MultipleProduc" +
      "tResponse\022K\n\026FindProductsByCategory\022\021.pr" +
      "oto.CategoryId\032\036.proto.MultipleProductRe" +
      "sponse\022M\n\026FindRecommendedProduct\022\023.proto" +
      ".ProductEmpty\032\036.proto.MultipleProductRes" +
      "ponse\022F\n\017FindTopProducts\022\023.proto.Product",
      "Empty\032\036.proto.MultipleProductResponse\022\'\n" +
      "\004Save\022\016.proto.Product\032\017.proto.Response\022)" +
      "\n\006Update\022\016.proto.Product\032\017.proto.Respons" +
      "e\022+\n\006Delete\022\020.proto.ProductId\032\017.proto.Re" +
      "sponseB+\n\025id.grocery.tunas.grpcP\001Z\020/serv" +
      "ice/productb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ResponseOuterClass.getDescriptor(),
          CategoryOuterClass.getDescriptor(),
        }, assigner);
    internal_static_proto_Product_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_Product_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Product_descriptor,
        new java.lang.String[] { "Name", "Id", "Category", "ImageUrl", "Price", "Weight", "CategoryId", "PerUnit", "Description", "IsRecommended", "IsTop", });
    internal_static_proto_ProductId_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_ProductId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ProductId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_proto_ProductEmpty_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_ProductEmpty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ProductEmpty_descriptor,
        new java.lang.String[] { });
    internal_static_proto_ProductResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_proto_ProductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_ProductResponse_descriptor,
        new java.lang.String[] { "Status", "Message", "Data", });
    internal_static_proto_MultipleProductResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_proto_MultipleProductResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_MultipleProductResponse_descriptor,
        new java.lang.String[] { "Status", "Message", "Data", });
    ResponseOuterClass.getDescriptor();
    CategoryOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
