// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package id.tunas.grocery.grpc;

public interface ProductEmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.ProductEmpty)
    com.google.protobuf.MessageOrBuilder {
}
