// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package id.tunas.grocery.grpc;

public interface ProductOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.Product)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string id = 2;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 2;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string category = 3;</code>
   */
  java.lang.String getCategory();
  /**
   * <code>string category = 3;</code>
   */
  com.google.protobuf.ByteString
      getCategoryBytes();

  /**
   * <code>string imageUrl = 4;</code>
   */
  java.lang.String getImageUrl();
  /**
   * <code>string imageUrl = 4;</code>
   */
  com.google.protobuf.ByteString
      getImageUrlBytes();

  /**
   * <code>uint64 price = 5;</code>
   */
  long getPrice();

  /**
   * <code>uint32 weight = 6;</code>
   */
  int getWeight();

  /**
   * <code>string category_id = 7;</code>
   */
  java.lang.String getCategoryId();
  /**
   * <code>string category_id = 7;</code>
   */
  com.google.protobuf.ByteString
      getCategoryIdBytes();

  /**
   * <code>uint64 per_unit = 8;</code>
   */
  long getPerUnit();

  /**
   * <code>string description = 9;</code>
   */
  java.lang.String getDescription();
  /**
   * <code>string description = 9;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <code>bool is_recommended = 10;</code>
   */
  boolean getIsRecommended();

  /**
   * <code>bool is_top = 11;</code>
   */
  boolean getIsTop();
}
