// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transaction.proto

package id.tunas.grocery.grpc;

public final class TransactionOuterClass {
  private TransactionOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_TransactionUserId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_TransactionUserId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_TransactionId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_TransactionId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_TransactionProduct_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_TransactionProduct_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_TransactionBody_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_TransactionBody_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_TransactionProductDetail_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_TransactionProductDetail_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Transaction_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Transaction_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_TransactionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_TransactionResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_MultipleTransactionResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_MultipleTransactionResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021transaction.proto\022\005proto\032\016response.pro" +
      "to\"\037\n\021TransactionUserId\022\n\n\002id\030\001 \001(\t\"\033\n\rT" +
      "ransactionId\022\n\n\002id\030\001 \001(\t\"7\n\022TransactionP" +
      "roduct\022\022\n\nproduct_id\030\001 \001(\t\022\r\n\005total\030\002 \001(" +
      "\r\"O\n\017TransactionBody\022\017\n\007user_id\030\001 \001(\t\022+\n" +
      "\010products\030\002 \003(\0132\031.proto.TransactionProdu" +
      "ct\"\326\001\n\030TransactionProductDetail\022\014\n\004name\030" +
      "\001 \001(\t\022\n\n\002id\030\002 \001(\t\022\020\n\010category\030\003 \001(\t\022\020\n\010i" +
      "mageUrl\030\004 \001(\t\022\r\n\005price\030\005 \001(\004\022\016\n\006weight\030\006" +
      " \001(\r\022\023\n\013category_id\030\007 \001(\t\022\020\n\010per_unit\030\010 ",
      "\001(\004\022\023\n\013description\030\t \001(\t\022\r\n\005total\030\n \001(\r\022" +
      "\022\n\nproduct_id\030\013 \001(\t\"{\n\013Transaction\022\n\n\002id" +
      "\030\001 \001(\t\022\023\n\013total_price\030\002 \001(\004\022\030\n\020transacti" +
      "on_date\030\003 \001(\003\0221\n\010products\030\004 \003(\0132\037.proto." +
      "TransactionProductDetail\"X\n\023TransactionR" +
      "esponse\022\016\n\006status\030\001 \001(\t\022\017\n\007message\030\002 \001(\t" +
      "\022 \n\004data\030\003 \001(\0132\022.proto.Transaction\"`\n\033Mu" +
      "ltipleTransactionResponse\022\016\n\006status\030\001 \001(" +
      "\t\022\017\n\007message\030\002 \001(\t\022 \n\004data\030\003 \003(\0132\022.proto" +
      ".Transaction2\215\002\n\022TransactionService\022G\n\023F",
      "indByTransactionId\022\024.proto.TransactionId" +
      "\032\032.proto.TransactionResponse\022L\n\014FindByUs" +
      "erId\022\030.proto.TransactionUserId\032\".proto.M" +
      "ultipleTransactionResponse\022/\n\004Save\022\026.pro" +
      "to.TransactionBody\032\017.proto.Response\022/\n\006D" +
      "elete\022\024.proto.TransactionId\032\017.proto.Resp" +
      "onseB/\n\025id.grocery.tunas.grpcP\001Z\024/servic" +
      "e/transactionb\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          ResponseOuterClass.getDescriptor(),
        }, assigner);
    internal_static_proto_TransactionUserId_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_TransactionUserId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_TransactionUserId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_proto_TransactionId_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_TransactionId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_TransactionId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_proto_TransactionProduct_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_TransactionProduct_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_TransactionProduct_descriptor,
        new java.lang.String[] { "ProductId", "Total", });
    internal_static_proto_TransactionBody_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_proto_TransactionBody_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_TransactionBody_descriptor,
        new java.lang.String[] { "UserId", "Products", });
    internal_static_proto_TransactionProductDetail_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_proto_TransactionProductDetail_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_TransactionProductDetail_descriptor,
        new java.lang.String[] { "Name", "Id", "Category", "ImageUrl", "Price", "Weight", "CategoryId", "PerUnit", "Description", "Total", "ProductId", });
    internal_static_proto_Transaction_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_proto_Transaction_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Transaction_descriptor,
        new java.lang.String[] { "Id", "TotalPrice", "TransactionDate", "Products", });
    internal_static_proto_TransactionResponse_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_proto_TransactionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_TransactionResponse_descriptor,
        new java.lang.String[] { "Status", "Message", "Data", });
    internal_static_proto_MultipleTransactionResponse_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_proto_MultipleTransactionResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_MultipleTransactionResponse_descriptor,
        new java.lang.String[] { "Status", "Message", "Data", });
    ResponseOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
