// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transaction.proto

package id.tunas.grocery.grpc;

public interface TransactionBodyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.TransactionBody)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string user_id = 1;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>repeated .proto.TransactionProduct products = 2;</code>
   */
  java.util.List<TransactionProduct>
      getProductsList();
  /**
   * <code>repeated .proto.TransactionProduct products = 2;</code>
   */
  TransactionProduct getProducts(int index);
  /**
   * <code>repeated .proto.TransactionProduct products = 2;</code>
   */
  int getProductsCount();
  /**
   * <code>repeated .proto.TransactionProduct products = 2;</code>
   */
  java.util.List<? extends TransactionProductOrBuilder>
      getProductsOrBuilderList();
  /**
   * <code>repeated .proto.TransactionProduct products = 2;</code>
   */
  TransactionProductOrBuilder getProductsOrBuilder(
      int index);
}
