// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wishlist.proto

package id.tunas.grocery.grpc;

public interface UserAndWishlistIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.UserAndWishlistId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string wishlist_id = 1;</code>
   */
  java.lang.String getWishlistId();
  /**
   * <code>string wishlist_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getWishlistIdBytes();

  /**
   * <code>string user_id = 2;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();
}
