// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wishlist.proto

package id.tunas.grocery.grpc;

public interface WishlistDetailOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.WishlistDetail)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string product_id = 2;</code>
   */
  java.lang.String getProductId();
  /**
   * <code>string product_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getProductIdBytes();

  /**
   * <code>string user_id = 3;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 3;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();

  /**
   * <code>string name = 4;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 4;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>uint64 price = 5;</code>
   */
  long getPrice();

  /**
   * <code>uint32 weight = 6;</code>
   */
  int getWeight();

  /**
   * <code>string category = 7;</code>
   */
  java.lang.String getCategory();
  /**
   * <code>string category = 7;</code>
   */
  com.google.protobuf.ByteString
      getCategoryBytes();

  /**
   * <code>uint64 per_unit = 8;</code>
   */
  long getPerUnit();

  /**
   * <code>string image_url = 9;</code>
   */
  java.lang.String getImageUrl();
  /**
   * <code>string image_url = 9;</code>
   */
  com.google.protobuf.ByteString
      getImageUrlBytes();
}
