// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cart.proto

package id.grocery.tunas.grpc;

public interface CartEmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.CartEmpty)
    com.google.protobuf.MessageOrBuilder {
}
