// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: cart.proto

package id.grocery.tunas.grpc;

public interface CartAndUserIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.CartAndUserId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string user_id = 2;</code>
   */
  java.lang.String getUserId();
  /**
   * <code>string user_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getUserIdBytes();
}
