// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: category.proto

package id.grocery.tunas.grpc;

public final class CategoryOuterClass {
  private CategoryOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_Category_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_Category_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_CategoryId_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_CategoryId_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_EmptyCategory_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_EmptyCategory_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_CategoryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_CategoryResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_MultipleCategoryResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_MultipleCategoryResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016category.proto\022\005proto\032\016response.proto\"" +
      ";\n\010Category\022\020\n\010category\030\001 \001(\t\022\n\n\002id\030\002 \001(" +
      "\t\022\021\n\timage_url\030\003 \001(\t\"\030\n\nCategoryId\022\n\n\002id" +
      "\030\001 \001(\t\"\017\n\rEmptyCategory\"R\n\020CategoryRespo" +
      "nse\022\016\n\006status\030\001 \001(\t\022\017\n\007message\030\002 \001(\t\022\035\n\004" +
      "data\030\003 \001(\0132\017.proto.Category\"Z\n\030MultipleC" +
      "ategoryResponse\022\016\n\006status\030\001 \001(\t\022\017\n\007messa" +
      "ge\030\002 \001(\t\022\035\n\004data\030\003 \003(\0132\017.proto.Category2" +
      "\217\002\n\017CategoryService\0226\n\010FindById\022\021.proto." +
      "CategoryId\032\027.proto.CategoryResponse\022@\n\007F",
      "indAll\022\024.proto.EmptyCategory\032\037.proto.Mul" +
      "tipleCategoryResponse\022(\n\004Save\022\017.proto.Ca" +
      "tegory\032\017.proto.Response\022*\n\006Update\022\017.prot" +
      "o.Category\032\017.proto.Response\022,\n\006Delete\022\021." +
      "proto.CategoryId\032\017.proto.ResponseB,\n\025id." +
      "grocery.tunas.grpcP\001Z\021/service/categoryb" +
      "\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          id.grocery.tunas.grpc.ResponseOuterClass.getDescriptor(),
        }, assigner);
    internal_static_proto_Category_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_Category_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_Category_descriptor,
        new java.lang.String[] { "Category", "Id", "ImageUrl", });
    internal_static_proto_CategoryId_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_CategoryId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_CategoryId_descriptor,
        new java.lang.String[] { "Id", });
    internal_static_proto_EmptyCategory_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_proto_EmptyCategory_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_EmptyCategory_descriptor,
        new java.lang.String[] { });
    internal_static_proto_CategoryResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_proto_CategoryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_CategoryResponse_descriptor,
        new java.lang.String[] { "Status", "Message", "Data", });
    internal_static_proto_MultipleCategoryResponse_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_proto_MultipleCategoryResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_MultipleCategoryResponse_descriptor,
        new java.lang.String[] { "Status", "Message", "Data", });
    id.grocery.tunas.grpc.ResponseOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
