// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: category.proto

package id.grocery.tunas.grpc;

public interface CategoryResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.CategoryResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>.proto.Category data = 3;</code>
   */
  boolean hasData();
  /**
   * <code>.proto.Category data = 3;</code>
   */
  id.grocery.tunas.grpc.Category getData();
  /**
   * <code>.proto.Category data = 3;</code>
   */
  id.grocery.tunas.grpc.CategoryOrBuilder getDataOrBuilder();
}
