// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: category.proto

package id.grocery.tunas.grpc;

public interface CategoryIdOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.CategoryId)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
