// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: category.proto

package id.grocery.tunas.grpc;

public interface EmptyCategoryOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.EmptyCategory)
    com.google.protobuf.MessageOrBuilder {
}
