// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: wishlist.proto

package id.grocery.tunas.grpc;

public interface MultipleWishlistResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.MultipleWishlistResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>repeated .proto.WishlistDetail data = 3;</code>
   */
  java.util.List<id.grocery.tunas.grpc.WishlistDetail> 
      getDataList();
  /**
   * <code>repeated .proto.WishlistDetail data = 3;</code>
   */
  id.grocery.tunas.grpc.WishlistDetail getData(int index);
  /**
   * <code>repeated .proto.WishlistDetail data = 3;</code>
   */
  int getDataCount();
  /**
   * <code>repeated .proto.WishlistDetail data = 3;</code>
   */
  java.util.List<? extends id.grocery.tunas.grpc.WishlistDetailOrBuilder> 
      getDataOrBuilderList();
  /**
   * <code>repeated .proto.WishlistDetail data = 3;</code>
   */
  id.grocery.tunas.grpc.WishlistDetailOrBuilder getDataOrBuilder(
      int index);
}
