// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: product.proto

package id.grocery.tunas.grpc;

public interface ProductResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.ProductResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string status = 1;</code>
   */
  java.lang.String getStatus();
  /**
   * <code>string status = 1;</code>
   */
  com.google.protobuf.ByteString
      getStatusBytes();

  /**
   * <code>string message = 2;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 2;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>.proto.Product data = 3;</code>
   */
  boolean hasData();
  /**
   * <code>.proto.Product data = 3;</code>
   */
  id.grocery.tunas.grpc.Product getData();
  /**
   * <code>.proto.Product data = 3;</code>
   */
  id.grocery.tunas.grpc.ProductOrBuilder getDataOrBuilder();
}
