// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transaction.proto

package id.grocery.tunas.grpc;

public interface TransactionProductOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.TransactionProduct)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string product_id = 1;</code>
   */
  java.lang.String getProductId();
  /**
   * <code>string product_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getProductIdBytes();

  /**
   * <code>uint32 total = 2;</code>
   */
  int getTotal();
}
