### register
POST http://localhost:10001/api/v1/userModel/register
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### login
POST http://localhost:10001/api/v1/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### SHOP
POST http://localhost:10001/api/v1/shop
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDoxMDAwMS9hcGkvdjEvbG9naW4iLCJ4LWN1c3RvbS1pZCI6eyJ1c2VySWQiOiI1Y2IzYjIwOS0zOWZmLTQ5NjUtOTYwNi1mMmUwMGViYzEzMzIifSwiZXhwIjoxNjkyNzk0MjkzfQ.RiMq4yqoPRiBkCyWoGBY70JXzFwPFZxvKZS8aq1B-40

{
  "name": "Tunas Shop",
  "imageUrl": "",
  "address":  ""
}

### GET ALL USERS
GET http://localhost:10001/api/v1/userModel/all
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDoxMDAwMS9hcGkvdjEvbG9naW4iLCJ4LWN1c3RvbS1pZCI6eyJ1c2VySWQiOiI1Y2IzYjIwOS0zOWZmLTQ5NjUtOTYwNi1mMmUwMGViYzEzMzIifSwiZXhwIjoxNjkyNzk0MjkzfQ.RiMq4yqoPRiBkCyWoGBY70JXzFwPFZxvKZS8aq1B-40


### REFRESH TOKEN
GET http://localhost:10001/api/v1/token
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDoxMDAwMS9hcGkvdjEvbG9naW4iLCJ4LWN1c3RvbS1pZCI6eyJ1c2VySWQiOiI1Y2IzYjIwOS0zOWZmLTQ5NjUtOTYwNi1mMmUwMGViYzEzMzIifSwiZXhwIjoxNjkyNzk0MjkzfQ.RiMq4yqoPRiBkCyWoGBY70JXzFwPFZxvKZS8aq1B-40
