version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: grocery
      PGDATA: /var/lib/postgresql/data/ecomerce
    ports:
      - "5432:5432"
    volumes:
      - tunas_pgdb_data:/var/lib/postgresql/data/ecomerce
    networks:
      - tunas-network

networks:
  tunas-network:
    driver: bridge

volumes:
  tunas_pgdb_data:
