version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: DBTunasGrocery
      PGDATA: /var/lib/postgresql/data/ecomerce
    ports:
      - "5432:5432"
    volumes:
      - tunas_pgdb_data:/var/lib/postgresql/data/ecomerce
    networks:
      - tunas-network
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
networks:
  tunas-network:
    driver: bridge

volumes:
  tunas_pgdb_data:
