version: '3'
services:
  user-service:
    image: grocery-user-service
    ports:
      - "8080:8080"
    environment:
      GRPC_SERVER_HOST: product-service
      GRPC_SERVER_PORT: 50051
      JDBC_USERNAME: postgres
      JDBC_PASSWORD: secret
      JDBC_URL: jdbc:postgresql://db:5432/grocery-user-service
      DB_SCHEMA: public
    links:
      - product-service
      - db
    networks:
      - tunas-network
  product-service:
    image: grocery-product-service
    ports:
      - "127.0.0.1:50051:50051"
    environment:
      DB_USERNAME: postgres
      DB_PASS: secret
      DB_NAME: grocery-product-service
      DB_HOST: db
    networks:
      - tunas-network
    links:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: grocery
      PGDATA: /var/lib/postgresql/data/ecomerce
    ports:
      - "5432:5432"
    volumes:
      - tunas_pgdb_data:/var/lib/postgresql/data/ecomerce
    networks:
      - tunas-network

networks:
  tunas-network:
    driver: bridge

volumes:
  tunas_pgdb_data:
