version: '3'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: DBTunasKasir
      PGDATA: /var/lib/postgresql/data/grocery
    ports:
      - 5432:5432
    volumes:
      - tunas_pgdb_data:/var/lib/postgresql/data/grocery
    networks:
      - tunas-network

networks:
  tunas-network:
    driver: bridge

volumes:
  tunas_pgdb_data:
