version: '3'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: postgres
      POSTGRES_DB: DBTunasGrocery
      PGDATA: /var/lib/postgresql/data/ecomerce
    ports:
      - "5432:5432"
    volumes:
      - tunas_pgdb_data:/var/lib/postgresql/data/ecomerce
    networks:
      - tunas-network
  mongo:
    image: mongo:5.0.6
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: tunasReport
    volumes:
      - tunas_collection:/etc/mongo
    ports:
      - "27017:27017"
  redis:
    image: redis:alpine3.15
    volumes:
      - tunas_cache:/data
    ports:
      - "6379:6379"
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    ports:
      - "5672:5672"
      - "15672:15672"
networks:
  tunas-network:
    driver: bridge

volumes:
  tunas_pgdb_data:
  tunas_collection:
  tunas_cache: