### register
POST http://localhost:8080/api/v1/userModel/register
Content-Type: application/json

{
  "username": "admin",
  "password": "rahasia"
}

### login
POST http://localhost:8080/api/v1/login
Content-Type: application/json

{
  "username": "admin",
  "password": "rahasia"
}

###
GET http://localhost:8080/api/v1/userModel/token
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhZG1pbiIsInJvbGVzIjpbXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgwL2FwaS92MS9sb2dpbiIsImV4cCI6MTY1Njg0MjczOX0.Mi7tlgJmUZxVrQ7DANwZMg0ViphUJVRX-gSRrSEKDqo
