apiVersion: apps/v1
kind: Deployment
metadata:
  name: grocery-application-deployment
spec:
  selector:
    matchLabels:
      app: grocery-application
  replicas: 1
  template:
    metadata:
      labels:
        app: grocery-application
    spec:
      containers:
        - name: grocery-application
          image: ramdanariadi/grocery
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_HOST
              value: $(GROCERY_DATABASE_SERVICE_SERVICE_HOST)
            - name: DATABASE_PORT
              value: $(GROCERY_DATABASE_SERVICE_SERVICE_PORT)
            - name: DATABASE_NAME
              value: grocery
            - name: DATABASE_USERNAME
              value: postgres
            - name: DATABASE_PASSWORD
              value: secret
          resources:
            limits:
              memory: 1Gi
              cpu: "2"

---

apiVersion: v1
kind: Service
metadata:
  name: grocery-application-service
spec:
  type: NodePort
  selector:
    app: grocery-application
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 30001