apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grocery-persistent-volume-claim
spec:
  volumeName: grocery-persistent-volume
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: grocery-database
spec:
  selector:
    matchLabels:
      app: grocery-database
  replicas: 1
  template:
    metadata:
      labels:
        app: grocery-database
    spec:
      containers:
        - name: grocery-postgres-database
          image: postgres:13-alpine
          ports:
            - containerPort: 5432
              name: "postgres"
          volumeMounts:
            - mountPath: "var/lib/postgresql/data"
              name: grocery-postgres-data-storage
          env:
            - name: POSTGRES_PASSWORD
              value: secret
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: grocery
            - name: PGDATA
              value: /var/lib/postgresql/data/ecommerce
          resources:
            limits:
              memory: 128Mi
              cpu: 100m
      volumes:
        - name: grocery-postgres-data-storage
          persistentVolumeClaim:
            claimName: grocery-persistent-volume-claim

---

apiVersion: v1
kind: Service
metadata:
  name: grocery-database-service
spec:
  type: NodePort
  selector:
    app: grocery-database
  ports:
    - name: grocery-database-postgres-port
      protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30432