apiVersion: v1
kind: Pod
metadata:
  name: myapp2
  labels:
    app: myapp2
spec:
  containers:
    - name: myapp2
      image: ramdanariadi/myapp2
      ports:
        - containerPort: 10001

---

apiVersion: v1
kind: Service
metadata:
  name: myapp2-service
spec:
  selector:
    app: myapp2
  ports:
    - protocol: TCP
      port: 10001
      targetPort: 10001