apiVersion: v1
kind: PersistentVolume
metadata:
  name: grocery-persistent-volume
spec:
  storageClassName: do-block-storage
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /grocery-postgres-data