apiVersion: v1
kind: PersistentVolume
metadata:
  name: grocery-persistent-volume
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/c/Users/ramdan/Documents/tunas/tunas-pv-space